# Generated by Django 5.0.7 on 2024-07-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
